import createActionTypes from './utils';

export const AUTHENTICATION_TOKENS_LIST = createActionTypes('AUTHENTICATION_TOKENS_LIST');

export const AUTHENTICATION_TOKENS_CREDENTIALS_SET = 'AUTHENTICATION_TOKENS_CREDENTIALS_SET';
export const AUTHENTICATION_TOKENS_CREDENTIALS_CLEAR = 'AUTHENTICATION_TOKENS_CREDENTIALS_CLEAR';

export const AUTHENTICATION_TOKENS_MODALS_OPEN = 'AUTHENTICATION_TOKENS_MODALS_OPEN';

export const AUTHENTICATION_TOKENS_MODALS_CLOSE = 'AUTHENTICATION_TOKENS_MODALS_CLOSE';
export const AUTHENTICATION_TOKENS_FILTER_SET = 'AUTHENTICATION_TOKENS_FILTER_SET';
export const AUTHENTICATION_TOKENS_FILTER_CLEAR = 'AUTHENTICATION_TOKENS_FILTER_CLEAR';
